// `${location.protocol}//${location.hostname}:${location.port}/egucepayment/restapi`
// 'http://localhost:8090/egucepayment/restapi'
export const Config = Object.freeze({
    BASE_REST_API: '/egucepayment/restapi/',
    PROTOCOL: location.protocol,
    PORT: 58080, // location.port
    REST_API_HOST: location.hostname,
    AUTHORIZATION_PREFIX: '',
    AUTHORIZATION_KEY: 'X-Authorization',
    LOCALE_KEY: 'locale',
    JWT_TOKEN_KEY: 'token',
    USER_LOGIN_KEY: 'login',
    USER_ROLES_KEY: 'roles',
    FULL_USER_NAME_KEY: 'USER_NAME',
    USER_PASSWORD_KEY: 'password',
    BROWSER_FINGER_PRINT_KEY: 'browser_finger_print',
    ASSET_PAYMENT_MODE_CODE: 'ASSET',
    TRANSFER_PAYMENT_MODE_CODE: 'TRANSFER',
    BC_PAYMENT_MODE_CODE: 'BANK_CARD',
    MOBILE_PAYMENT_MODE_CODE: 'MOBILE',
    CASHIER_PAYMENT_MODE_CODE: 'CHASHIER',
    GLOBAL_PERIOD: 60000,
    NOT_ACCEPTABLE_STATUS_CODE: 406,
    UNAUTHORIZED_STATUS_CODE: 401,
    FORBIDDEN_STATUS_CODE: 403,
    NOT_FOUND_STATUS_CODE: 404,
    SERVER_ERROR_STATUS_CODE: 500,
    OK_STATUS_CODE: 200,
    ELAPSED_IDLE_TIME_KEY: 'ELAPSED_IDLE_TIME',
    IDLE_TIMEOUT: 1800,
    CURRENT_LANGUAGE_KEY: 'CURRENT_LANGUAGE',
    TIMER_BEFORE_GO_HOME: 30000,
    ALERT_TIMER: 9000,
    LAZY_TIMER: 250,
    SESSION_EXPIRED_PARAM_VALUE: 'session_expired',
    LOGOUT_PARAM_VALUE: 'logout',
    LOGIN_ROUTE_PARAM_KEY: 'param',
    ERROR_PAGE_ROUTE_PARAM_KEY: 'status',
    CONTENT_TYPE_HEADER: "Content-Type",
    FILE_DOWNLOAD_HEADER: "Content-Disposition",
    MEDIA_TYPE_EXCEL: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    MEDIA_TYPE_PDF: "application/pdf",
    // partners types
    PARTNER_TYPE_PRINCIPAL: 'PRINCIPAL',
    PARTNER_TYPE_BENEFICIARY: 'BENEFICIARY',
    PARTNER_TYPE_BANK: 'BANK',
    PARTNER_TYPE_BANK_AGENCY: 'BANK_AGENCY',
    PARTNER_TYPE_ADMIN: 'ADMIN',
    // payment modes
    PM_ASSET: 'ASSET',
    PM_CAMPOST_WALLET: 'CAMPOST_WALLET',
    PM_VISA_UBA: 'VISA_UBA',
    PM_PRINCIPAL_TRANSFER: 'E_TRANSFER',
    //
    PM_COUNTER_TRANSFER: 'COUNTER_TRANSFER',
    PM_COUNTER_TRANSFER_LABEL: 'transfer',
    PM_COUNTER_TRANSFER_PREF_LABEL: 'transfer.order.number',
    //
    PM_CASH: 'CASH',
    PM_CASH_LABEL: 'cash.payment',
    PM_CASH_PREF_LABEL: 'receipt.number',
    //
    PM_CHECK: 'CHECK',
    PM_CHECK_LABEL: 'check.payment',
    PM_CHECK_PREF_LABEL: 'check.number',
    // i18n
    CONFIRM_DELETE_INVOICE_FR: '',
    CONFIRM_DELETE_INVOICE_EN: '',
    INVOICE_DELETED_FR: '',
    INVOICE_DELETED_EN: '',
    // invoices status
    INVOICE_UNPAID: 'unpaid',
    INVOICE_PAYMENT_STARTED: 'payment.started',
    INVOICE_PAYMENT_CANCELED: 'payment.canceled',
    INVOICE_PAYMENT_REJECTED: 'payment.rejected',
    INVOICE_PAID: 'paid',
    INVOICE_CLEARED: 'cleared',
    // roles
    ROLE_ADMIN: 'ADMIN',
    ROLE_DONNEUR_ORDRE: 'DONNEUR_ORDRE',
    ROLE_CONTROLEUR_DONNEUR_ORDRE: 'CONTROLEUR_DONNEUR_ORDRE',
    ROLE_AUDITEUR_DONNEUR_ORDRE: 'AUDITEUR_DONNEUR_ORDRE',
    ROLE_CAISSIER: 'CAISSIER',
    ROLE_CONTROLEUR_AGENCE: 'CONTROLEUR_AGENCE',
    ROLE_CONTROLEUR_BANQUE: 'CONTROLEUR_BANQUE',
    ROLE_AUDITEUR_BANQUE: 'AUDITEUR_BANQUE',
    ROLE_BENEFICIAIRE: 'BENEFICIAIRE',
    ROLE_DECIDEUR: 'DECIDEUR'
});

