CREATE TABLE SIAT_CO.STAMP_SIGNATURE(
    SIAT_CO.ID NUMBER(19,0) DEFAULT STAMP_SIGNATURE_SEQ.NEXTVAL,,
    SIAT_CO.IMAGE_NAME VARCHAR2(255) NOT NULL,
	SIAT_CO.IMAGE_VALUE BLOB NOT NULL,
	SIAT_CO.CREATION_DATE DATE,
    PRIMARY KEY("ID")
)

Insert into SIAT_CO.PARAMS (ID,NAME,CATEGORY,VALUE) values ((SELECT MAX(ID) + 1 FROM PARAMS),'CHOICE_GLOBAL_STAMP','GN','NON');
Insert into SIAT_CO.PARAMS (ID,NAME,CATEGORY,VALUE) values ((SELECT MAX(ID) + 1 FROM PARAMS),'CHOICE_GLOBAL_URL_STAMP','GN','');


======== SUR WEBGUCE ========


ALTER TABLE WEBGUCE.CO_GOODS ADD (GOOD_LINE_NUMBER NUMBER(8));
ALTER TABLE WEBGUCE.CO_GOODS ADD (GOOD_NET_WEIGHT NUMBER(18,4));
ALTER TABLE WEBGUCE.CO_GOODS ADD (GOOD_DESCRIPTION VARCHAR2(255 BYTE));
ALTER TABLE WEBGUCE.CO_GOODS ADD (GOOD_WEIGHT_UNIT VARCHAR2(35 BYTE));
ALTER TABLE WEBGUCE.CO_GOODS RENAME COLUMN GOOD_GROSS_MASS TO GOOD_NET_WEIGHT;


Insert into SIAT_CO.FILE_ITEM_FIELD (ID,CODE,LABEL_EN,LABEL_FR,REPEATABLE,UPDATABLE,FILE_TYPE_ID,GROUP_ID) values ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),'CODE_UNITE_POIDS','Code Unit Weight','Code Unité de poids','0','1',(select id from FILE_TYPE where code='CO_GCO'),'1');
Insert into SIAT_CO.FILE_ITEM_FIELD (ID,CODE,LABEL_EN,LABEL_FR,REPEATABLE,UPDATABLE,FILE_TYPE_ID,GROUP_ID) values ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),'LIBELLE_UNITE_POIDS','Unit Weight','Unité de poids','0','1',(select id from FILE_TYPE where code='CO_GCO'),'1');
Insert into SIAT_CO.FILE_ITEM_FIELD (ID,CODE,LABEL_EN,LABEL_FR,REPEATABLE,UPDATABLE,FILE_TYPE_ID,GROUP_ID) values ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),'POIDS_BRUT','Brut weight','Poids Brut','0','1',(select id from FILE_TYPE where code='CO_GCO'),'1');
Insert into SIAT_CO.FILE_ITEM_FIELD (ID,CODE,LABEL_EN,LABEL_FR,REPEATABLE,UPDATABLE,FILE_TYPE_ID,GROUP_ID) values ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),'POIDS_NET','Net weight','POids Net','0','1',(select id from FILE_TYPE where code='CO_GCO'),'1');
Insert into SIAT_CO.FILE_ITEM_FIELD (ID,CODE,LABEL_EN,LABEL_FR,REPEATABLE,UPDATABLE,FILE_TYPE_ID,GROUP_ID) values ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),'DESCRIPTION','Description','Description','0','1',(select id from FILE_TYPE where code='CO_GCO'),'1');
