CREATE TABLE SIAT_CO.STAMP_SIGNATURE(
    SIAT_CO.ID NUMBER(19,0) DEFAULT STAMP_SIGNATURE_SEQ.NEXTVAL,,
    SIAT_CO.IMAGE_NAME VARCHAR2(255) NOT NULL,
	SIAT_CO.IMAGE_VALUE BLOB NOT NULL,
	SIAT_CO.CREATION_DATE DATE,
    PRIMARY KEY("ID")
)